package org.spacehub.entities.Notification;

public enum NotificationType {
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    FRIEND_REJECTED,
    COMMUNITY_INVITE,
    COMMUNITY_JOINED,
    COMMUNITY_REQUEST_ACCEPTED,
    COMMUNITY_INVITE_REVOKED,
    LOCAL_GROUP_INVITE,
    SYSTEM_UPDATE,
    LOCAL_GROUP_JOIN,
    REPORT_MESSAGE_DIRECT,
    REPORT_MESSAGE_CHATROOM,
    REPORT_REVIEW,
    COMMUNITY,
    COMMUNITY_MEMBER_LEFT,
    COMMUNITY_MEMBER_REMOVED,
    FRIEND_REMOVED
}
